language: java

jdk: oraclejdk8

sudo: required
dist: trusty
addons:
  chrome: stable
before_install:
  - # start web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=8001 http://localhost &

install: true

script: mvn clean install -DskipDocker

branches:
  only: master

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.m2/wrapper/

notifications:
  email: false