language: java

jdk: oraclejdk8

sudo: required

install: true

script: mvn clean install -DskipDocker

branches:
  only: master

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.m2/wrapper/

notifications:
  email: false