language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3

sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chown root /opt/google/chrome/chrome-sandbox ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod 4755 /opt/google/chrome/chrome-sandbox; fi

install: true

script: mvn clean install

branches:
  only: master

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.m2/wrapper/

notifications:
  email: false