language: java

sudo: false

jdk:
  - oraclejdk8

install: true

script: mvn clean install -DskipTests -DskipDocker

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false