language: java

sudo: false

jdk: oraclejdk8

install: true

script: mvn clean install -DskipTests -DskipDocker

branches:
  only: master

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.m2/wrapper/

notifications:
  email: false