language: java

sudo: false

jdk:
  - oraclejdk8

before_install:
  - phantomjs --version
  - export DISPLAY=:99.0

install: true

script: mvn clean install -DskipDocker

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false